GET https://api.itsukaralink.jp//livers/32.json
#{
#  "status": "ok",
#  "data": {
#    "liver": {
#      "id": 32,
#      "name": "月ノ美兎",
#      "description": "高校2年生。性格はツンデレだが根は真面目な学級委員。本人は頑張っているが少し空回り気味で、よく発言した後で言いすぎたかもと落ち込んだりする。",
#      "avatar": "https://s3-ap-northeast-1.amazonaws.com/liver-icons/400x400/Tsukino_Mito.png",
#      "public": 1,
#      "color": "#e43f3b",
#      "position": 10
#    },
#    "events": [
#      {
#        "id": 258,
#        "name": "テスト-9163c47b99fd",
#        "description": "テストデータ0f7688938a14",
#        "public": 1,
#        "url": "https://www.youtube.com/watch?v=d1551fe808597773138f7bc1",
#        "start_date": "2019-01-28T00:00:00.000+09:00",
#        "end_date": "2019-01-28T01:00:00.000+09:00",
#        "recommend": false
#      }
#    ],
#    "user_liver": null,
#    "liver_youtube_channel": {
#      "id": 32,
#      "liver_id": 32,
#      "channel": "UCD-miitqNY3nyukJ4Fnf4_A"
#    }
#  }
#}
